# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JfT7lD3evcJzuHS2Q5xRaRglIw3KUmt
"""

import pandas as pd
import requests
from datetime import datetime
import openpyxl
from openpyxl.styles import Alignment, Font

# Hàm khôi phục văn bản Abstract từ Inverted Index của OpenAlex
def get_abstract(inv_index):
    if not inv_index:
        return None
    word_list = []
    for word, positions in inv_index.items():
        for pos in positions:
            word_list.append((pos, word))
    word_list.sort(key=lambda x: x[0])
    return " ".join([w[1] for w in word_list])

records = []
page = 1

# Lặp cho đến khi thu thập đủ 50 hồ sơ hoàn toàn sạch
while len(records) < 50 and page <= 20:
    url = f"https://api.openalex.org/works?filter=has_doi:true,has_abstract:true,has_fulltext:true&per_page=50&page={page}"
    response = requests.get(url)
    data = response.json()
    results = data.get('results', [])

    for item in results:
        # 1. Trích xuất Tác giả & Mã ORCID thật
        authorships = item.get('authorships', [])
        authors_list = []
        orcids_list = []

        for a in authorships:
            author_name = a.get('author', {}).get('display_name')
            orcid_url = a.get('author', {}).get('orcid')
            if author_name and orcid_url:
                authors_list.append(author_name)
                orcids_list.append(orcid_url.split('/')[-1]) # Lấy chuỗi mã 0000-000X-XXXX-XXXX

        # Bắt buộc phải có tác giả VÀ mã ORCID đầy đủ
        if not authors_list or not orcids_list or len(authors_list) != len(orcids_list):
            continue

        # 2. Trích xuất các trường dữ liệu còn lại
        title = item.get('title')

        doi_raw = item.get('doi')
        doi = doi_raw.replace('https://doi.org/', '') if doi_raw else None

        publish_year = item.get('publication_year')

        primary_location = item.get('primary_location') or {}
        source = primary_location.get('source') or {}
        venue = source.get('display_name')

        primary_topic = item.get('primary_topic') or {}
        field = primary_topic.get('field', {}).get('display_name') or primary_topic.get('domain', {}).get('display_name')

        concepts = item.get('concepts', [])
        keywords_list = [c.get('display_name') for c in concepts[:5] if c.get('display_name')]
        keywords = ", ".join(keywords_list) if keywords_list else None

        abstract = get_abstract(item.get('abstract_inverted_index'))

        open_access = item.get('open_access') or {}
        pdf_url = open_access.get('oa_url') or primary_location.get('pdf_url')

        source_type_raw = item.get('type')
        if source_type_raw in ['article', 'journal-article']:
            source_type = 'journal'
        elif source_type_raw in ['proceedings-article', 'conference-paper']:
            source_type = 'conference'
        else:
            source_type = 'preprint'

        # 3. ĐIỀU KIỆN LỌC SẠCH KHẮT KHE: Bắt buộc TẤT CẢ các trường phải có dữ liệu
        if all([title, doi, authors_list, orcids_list, publish_year, venue, field, keywords, abstract, pdf_url]):
            records.append({
                "id": len(records) + 1,
                "title": title,
                "doi": doi,
                "authors": "; ".join(authors_list),
                "author_orcids": "; ".join(orcids_list),
                "publish_year": publish_year,
                "venue": venue,
                "field": field,
                "keywords": keywords,
                "abstract": abstract,
                "pdf_url": pdf_url,
                "source_type": source_type,
                "created_at": datetime.now().strftime("%Y-%m-%d")
            })

            if len(records) == 50:
                break
    page += 1

# Xuất dữ liệu ra Excel & Căn chỉnh giao diện
df = pd.DataFrame(records)

file_name = "research_profiles.xlsx"
with pd.ExcelWriter(file_name, engine='openpyxl') as writer:
    df.to_excel(writer, index=False, sheet_name='research_profile')
    worksheet = writer.sheets['research_profile']

    # In đậm tiêu đề
    for cell in worksheet[1]:
        cell.font = Font(bold=True)

    # Tự động dãn cột & bật ngắt dòng
    for col in worksheet.columns:
        col_letter = col[0].column_letter
        max_len = max(len(str(cell.value or '')) for cell in col)

        if col_letter in ['A', 'E', 'F', 'L', 'M']:
            adjusted_width = max(max_len + 3, 12)
        else:
            adjusted_width = min(max(max_len + 3, 15), 45)

        worksheet.column_dimensions[col_letter].width = adjusted_width
        for cell in col:
            cell.alignment = Alignment(vertical='top', wrap_text=True)

print(f"Đã cào {len(records)} hồ sơ")


import sqlite3
import pandas as pd

# 1. Đọc file Excel 50 hồ sơ
df = pd.read_excel("research_profiles.xlsx")

# 2. Tạo một database SQLite nằm ngay trong Colab có tên là "techlinkvn.db"
conn = sqlite3.connect("techlinkvn.db")

# 3. Đẩy toàn bộ dữ liệu từ Pandas DataFrame vào bảng SQL có tên là "papers"
df.to_sql("papers", conn, if_exists="replace", index=False)

# 4. Thử viết một câu lệnh SQL để truy vấn dữ liệu trực tiếp trong Colab luôn!
query = "SELECT title, venue, field FROM papers WHERE field = 'Vật liệu mới' LIMIT 3"
result_df = pd.read_sql(query, conn)

print("--- KẾT QUẢ TRUY VẤN SQL TRÊN COLAB ---")
print(result_df)

# Đóng kết nối
conn.close()

import sqlite3
import pandas as pd
from IPython.display import display

# 1. Mở kết nối đến database SQLite
conn = sqlite3.connect("techlinkvn.db")

# 2. Lấy toàn bộ dữ liệu từ bảng papers
query = "SELECT * FROM papers"
result_df = pd.read_sql(query, conn)

# 3. Đánh lại thứ tự
result_df.index = range(1, len(result_df) + 1)

# 4. Cấu hình để bảng hiển thị rộng hết cỡ, không bị thu gọn hay cắt bớt cột
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)

print("--- TOÀN BỘ 50 BÀI BÁO ---")
display(result_df)

# Đóng kết nối
conn.close()